### ISSUE TITLE
Does not Work

### ISSUE THREAD

**Issue by pjobson** [OnionIoT/omega2-hostname-tool#1]
The host name exists in these files, running the hostname tool does not change anything.

        option hostname 'Omega-ADBD'
    ./etc/config/system
        option ssid 'Omega-ADBD'
    ./etc/config/wireless
        option hostname 'Omega-ADBD'
    ./overlay/upper/etc/config/system
        option ssid 'Omega-ADBD'
    ./overlay/upper/etc/config/wireless

**Comment by greenbreakfast** [comment]
This tool ensures that the hostname is properly written to the above mentioned files.
